[calendar] Room might be None. If so, skip room attribute.
Recognized because an exception was thrown in production. Excerpt:

> Internal Server Error: /glt19/speaker/VXNRDD/talks.ics
>
> AttributeError at /glt19/speaker/VXNRDD/talks.ics
> 'NoneType' object has no attribute 'name'
>
> Request Method: GET
> Request URL: http://pretalx.linuxtage.at/glt19/speaker/VXNRDD/talks.ics
> Django Version: 2.1.4
> Python Executable: /usr/bin/python3
> Python Version: 3.7.3
>
> […]
>
> File "/var/pretalx/.local/lib/python3.7/site-packages/pretalx/agenda/views/speaker.py" in get
>   58.             slot.build_ical(cal)
>
> File "/var/pretalx/.local/lib/python3.7/site-packages/pretalx/schedule/models/slot.py" in build_ical
>   136.         vevent.add('location').value = str(self.room.name)
>
> Exception Type: AttributeError at /glt19/speaker/VXNRDD/talks.ics
> Exception Value: 'NoneType' object has no attribute 'name'